name: 'Build PHP 8.2'
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '30 23 * * *'
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip-8.2')"
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x64
            target: obj-x64
            config: nts-windows-vs16-x64
          - arch: x64
            target: obj-x64
            config: ts-windows-vs16-x64
          - arch: x64
            target: obj-x64
            config: nts-windows-vs16-x64-avx
          - arch: x86
            target: obj
            config: nts-windows-vs16-x86
          - arch: x86
            target: obj
            config: ts-windows-vs16-x86
    name: Build PHP
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@develop
        with:
          php-version: 8.2
          ini-values: disable_functions=mail
      - name: Test PHP
        run: php -v
      - name: Test php extensions
        run: php -m
      - name: Create Build Environment
        run: |
          New-Item -ItemType "directory" -Path C:\php-snap-build
          cd C:\php-snap-build
          git clone https://github.com/php/php-sdk-binary-tools.git php-sdk
          git clone https://github.com/php/web-rmtools.git rmtools
          New-Item -ItemType "directory" -Path C:\php-snap-build\${{ matrix.target }}
          New-Item -ItemType "directory" -Path C:\php-snap-build\snap_82\vs16\${{ matrix.arch }}
          Copy-Item -Path C:\php-snap-build\rmtools\bin\rmtools_setvars.bat-dist -Destination C:\php-snap-build\rmtools\bin\rmtools_setvars.bat
          Copy-Item -Path C:\php-snap-build\rmtools\data\config\credentials_ftps.php-dist -Destination C:\php-snap-build\rmtools\data\config\credentials_ftps.php
      - name: Add InstantClient
        run: |
          $oci_dir="C:/php-snap-build/deps_aux/oracle/${{ matrix.arch }}"
          New-Item -ItemType "directory" -Path $oci_dir
          $suffix = 'windows'
          if ('${{ matrix.arch }}' -eq 'x86') {
            $suffix = 'nt'
          }
          Invoke-WebRequest -UseBasicParsing -Uri https://download.oracle.com/otn_software/nt/instantclient/instantclient-basiclite-$suffix.zip -OutFile $oci_dir\instantclient.zip
          Invoke-WebRequest -UseBasicParsing -Uri https://download.oracle.com/otn_software/nt/instantclient/instantclient-sdk-$suffix.zip -OutFile $oci_dir\sdk.zip
          Expand-Archive -Path $oci_dir\instantclient.zip -DestinationPath $oci_dir -Force
          Expand-Archive -Path $oci_dir\sdk.zip -DestinationPath $oci_dir -Force
          Get-ChildItem $oci_dir -Filter 'instantclient*' | ?{ $_.PSIsContainer } | Rename-Item -NewName instantclient_19_9
      - name: Patch Tools
        run: |
          $git_location="C:\Program Files\Git\cmd\git.exe"
          $tar_location="C:\Program Files\Git\usr\bin\tar.exe"
          $task_location="C:\php-snap-build\rmtools\bin\snapshot_task.bat"
          $git_script_location="C:\php-snap-build\rmtools\include\Git.php"
          $snap_script_location="C:\php-snap-build\rmtools\script\snap.php"
          $branch_script_location="C:\php-snap-build\rmtools\include\Branch.php"
          $config_location="C:\php-snap-build\rmtools\data\config\branch\${{ matrix.arch }}\php82.ini"
          ((Get-Content -path $git_script_location -Raw) -replace "c:\\apps\\git\\bin\\git.exe", $git_location) | Set-Content -Path $git_script_location
          ((Get-Content -path $git_script_location -Raw) -replace "c:\\apps\\git\\bin\\tar.exe", $tar_location) | Set-Content -Path $git_script_location
          ((Get-Content -path $task_location -Raw) -replace ">> %LOG_FILE% 2<&1", "") | Set-Content -Path $task_location
          ((Get-Content -path $snap_script_location -Raw) -replace "0, 7", "0, 10") | Set-Content -Path $snap_script_location
          ((Get-Content -path $branch_script_location -Raw) -replace "0, 7", "0, 10") | Set-Content -Path $branch_script_location
          ((Get-Content -path $config_location -Raw) -replace "pgo=1", "pgo=0") | Set-Content -Path $config_location
      - name: build PHP
        run: |
          C:\php-snap-build\php-sdk\bin\vswhere
          $ErrorActionPreference = "Stop"
          & C:\php-snap-build\php-sdk\phpsdk-vs16-${{ matrix.arch }}.bat -t C:\php-snap-build\rmtools\bin\snapshot_task.bat --task-args "php82 ${{ matrix.config }}"
      - name: Collect Artifacts
        run: |
          New-Item -ItemType "directory" -Path builds
          Get-ChildItem C:\php-snap-build\${{ matrix.target }}\* -Recurse -Include php-*.zip | Foreach-Object { Copy-Item -Path $_ -Destination .\builds }
          Copy-Item -Path C:\php-snap-build\rmtools\data\db\PHP-8.2.json -Destination .\builds\${{ matrix.config }}.json
          if((Get-ChildItem .\builds\*.zip).Count -lt 5) {
            exit 1
          }
          $php_version = Invoke-RestMethod https://raw.githubusercontent.com/php/php-src/PHP-8.2/main/php_version.h | Where-Object { $_  -match 'PHP_VERSION "(.*)"' } | Foreach-Object {$Matches[1]}
          (Get-Content .\builds\${{ matrix.config }}.json | ConvertFrom-Json).revision_last > COMMIT
          Get-ChildItem .\builds\* -Include ("php-$php_version*.zip", "php-master*.zip") | Foreach-Object { Compress-Archive -update COMMIT $_ }
          Get-ChildItem .\builds\*.zip | Foreach-Object {
            if ($_.Name -match '.*(rc|RC)\d*-dev.*') {
              Copy-Item -Path $_ -Destination (Join-Path -Path builds -ChildPath ($_.Name -replace '(rc|RC)\d+', '')) -Force
            }
          }
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.config }}
          path: builds
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create builds directory  
        run: mkdir builds

      - name: Download artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          path: builds

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install cloudsmith-cli
        run: pip install --upgrade cloudsmith-cli

      - name: Release
        run: bash scripts/release.sh
        env:          
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
          GITHUB_MESSAGE: ${{ github.event.head_commit.message }}
          GITHUB_RELEASES: php8.2
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
